name: realestate
description: Real Estate App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  share_plus: ^6.3.0
  google_maps_flutter: ^2.2.2
  intl: ^0.18.0
  url_launcher: ^6.1.7
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.3.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  mockito: ^5.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:

  uses-material-design: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 20
